### ISSUE TITLE
Filter search results

### ISSUE THREAD

**Issue by konatabrk** [ruben2020/codequery4vscode#4]
Hello!
The extension is pretty nice in comparison with [scope4code](https://github.com/xulion/scope4code) and [cscope-code](https://github.com/SeungukShin/cscope-code), but the latter has a nice feature of filtering results based on the input string - I suppose it would be a nice feature for `codequery4vscode` as well.

For example, I want to find a definition of `getname` function in the Linux kernel source tree for 5.1.9 version. `codequery4vscode` finds a lot of various functions that contain a `getname` substring in its name, but I need to find `getname` and not `*getname*`, so it would be better to either make other options with strict searching or add a filtering functionality

Thanks in advance :)

**Comment by konatabrk** [comment]
Hmm, I guess it is a more general problem. Imagine, we have to find all callers of `strncpy_from_user` function (in the context of Linux kernel source code) - in that case, `codequery4vscode` will find `__arc_strncpy_from_user` calling which is not `strncpy_from_user` obviously.

Generally, I don't know where the actual problem is - `codequery4vscode` or `codequery`, but the results don't correspond to the request of `Function calling this function` and it happens in every API as I understood.

If I'm wrong and use it incorrectly, then my apologies, but I'm doing as stated in the readme

**Comment by ruben2020** [comment]
@merrychap Exact string search is available on `cqsearch` CLI but not yet added to the vscode plugin. I can easily add this. Thank you for the suggestion.

**Comment by konatabrk** [comment]
@ruben2020 Thank you, would be great :)

**Comment by ruben2020** [comment]
@merrychap New version 0.5.0 released with this feature (fuzzy search vs. exact search).
Please try it out and let me know if it meets your expectation, or if it has bugs. Thanks.
