### ISSUE TITLE
cqsearch -s works fine with my cq.db, but the plugin just keep reminding me `could not find ...cq.db`

### ISSUE THREAD

**Issue by huide9** [ruben2020/codequery4vscode#5]
Error:
    CodeQuery Error: Could not find/home/huide/mnt/aws-vdi/workspaces/tsg/src/inf-tsg/cq.db

The cq.db is located at `/home/huide/mnt/aws-vdi/workspaces/tsg/src/`   but not`.../tsg/src/inf-tsg/`

The following cli woks fine:
```cqsearch -s /home/huide/mnt/aws-vdi/workspaces/tsg/src/cq.db -p 1 -t <func_name>  -f```

How can I configure the plugin with correct -s path?  thank you.

Thanks for the amazing tool.

**Comment by ruben2020** [comment]
@huide9 Perhaps your base folder for source code, opened in Visual Studio Code, is `/home/huide/mnt/aws-vdi/workspaces/tsg/src/inf-tsg/`, which is why it is looking for `cq.db` there.

Please close the base folder in Visual Studio Code, and then open the base folder as `/home/huide/mnt/aws-vdi/workspaces/tsg/src/`

**Comment by huide9** [comment]
@ruben2020  thanks for the responding.  I did so, and hit `CodeQuery Error: /bin/sh: 1:cqsearch:not found`  it's actually locate at `/usr/bin/cqserach`, any suggestions?

**Comment by ruben2020** [comment]
@huide9 In the terminal, when you are on `/home/huide`, try `whereis cqsearch`. What does that give you?

**Comment by huide9** [comment]
My bad @ruben2020 ,  i'm using ssh + sshfs  remotely editing the code, vscode is running on local, all code are running on remote.  codequery installed on remote host but not local. (I keep wrongly testing it on a ssh session)  after install it on local linux, issue solved.  thanks a lot.

**Comment by ruben2020** [comment]
Thank you for your support @huide9
