### ISSUE TITLE
Feature Request: Allow setting (workspace-relative) location for cq.db file in extension prefs.

### ISSUE THREAD

**Issue by gwiede** [ruben2020/codequery4vscode#6]
As I already have .vscode programmed into all my .gitignore's and equivalents, I'd rather keep cq.db, cscope.out, and the other components that build cq.db all together inside `{workspace}/.vscode` or even better `{workspace}/.vscode/codequery/`.  I'd love to be able to set, ideally, workspace/`.vscode/codequery/` as where the plugin should look for the associate cq.db file to use.

**Comment by ruben2020** [comment]
This is a great idea.
The cq.db file can be placed either in workspace OR workspace/.vscode OR workspace/.vscode/codequery, and the extension can look for it in all these locations and make use of the first one that it can find.
This is a relatively minor change and the users will definitely find it useful. Request accepted!

**Comment by ruben2020** [comment]
@gwiede Version 0.7.0 released with this feature. Please allow for some time for the new version to be updated onto the Visual Studio Extensions marketplace.

Now you can place the `cq.db` file in either one of these 3 locations, and it will be automatically detected and used: `{workspace}/cq.db`, `{workspace}/.vscode/cq.db`, `{workspace}/.vscode/codequery/cq.db`.

This issue will be closed. If you find any problems with it, it can be reopened.
