### ISSUE TITLE
Feature request: add a full file patch in the search results

### ISSUE THREAD

**Issue by rmskkn** [ruben2020/codequery4vscode#8]
Can we add a full file path, not only the filename in the search results?
It can be really convenient to see the exact file if you find several files with the same file name in different locations.

Thanks a lot!

**Comment by ruben2020** [comment]
Is this referring to the GUI?

**Comment by rmskkn** [comment]
yes, It's related to vs code GUI.
After searching for a new item I see the file name only, not a full path as in the picture below:
https://pasteboard.co/VRRNkUb4gk6E.png

**Comment by ruben2020** [comment]
@galaxyraiser Feature implemented in codequery4vscode version 0.8.1.

**Comment by rmskkn** [comment]
> @galaxyraiser Feature implemented in codequery4vscode version 0.8.1.

Thanks!
